image: timbru31/node-alpine-git:latest

stages:
  - lint
  - build
  - publish

cache:
  paths:
    - node_modules/

before_script:
  - yarn

lint:
  except:
    - tags
  stage: lint
  script:
    - yarn eslint

# test:
#   except:
#     - tags
#   stage: test
#   script:
#     - yarn test


# build for mac:
#   stage: build installer
#   tags:
#     - osx
#     - shell
#   # only: master
#   script:
#     - nvm install 8.9
#     - yarn run build -m
#     - ls build/*.zip && ls build/*.dmg
#   artifacts:
#     paths:
#       - build/*.zip
#       - build/*.dmg


build:
  image: electronuserland/builder:wine
  stage: build
  only:
    - tags
  script:
    - yarn run build -lwm
  artifacts:
    expire_in: '1 hour'
    paths:
      - build/mnz-wallet-$CI_BUILD_TAG-setup.exe
      - build/mnz-wallet-$CI_BUILD_TAG-x86_64.AppImage
      - build/mnz-wallet-$CI_BUILD_TAG-mac.zip

publish:
  image: inetprocess/gitlab-release
  stage: publish
  only:
    - tags
  script:
    - gitlab-release --message 'MNZ Wallet $CI_BUILD_TAG Release'
      build/mnz-wallet-$CI_BUILD_TAG-setup.exe
      build/mnz-wallet-$CI_BUILD_TAG-x86_64.AppImage
      build/mnz-wallet-$CI_BUILD_TAG-mac.zip