stages:
  - build installer

# cache:
#   paths:
#     - node_modules/

before_script:
  - yarn config set registry http://mon-1:4873
  - echo $NPMRC | base64 -d > ~/.npmrc

# build for mac:
#   stage: build installer
#   tags:
#     - osx
#     - shell
#   # only: master
#   script:
#     - nvm install 8.9
#     - yarn
#     - yarn run build -m
#     - ls build/*.zip && ls build/*.dmg
#   artifacts:
#     paths:
#       - build/*.zip
#       - build/*.dmg


build for linux & windows:
  stage: build installer
  only: master
  script:
    - nvm install 8.9
    - yarn
    - yarn run build -lwm
    - scp -P 4242 build/*.exe mnzico@51.15.203.171:www/downloads
    - scp -P 4242 build/*.AppImage mnzico@51.15.203.171:www/downloads
    - scp -P 4242 build/*.zip mnzico@51.15.203.171:www/downloads